pipeline:
  build:
    image: golang
    commands:
      - ./build
  test:
    image: stolon-test-image
    commands:
      - INTEGRATION=1 PARALLEL=4 ETCD_BIN="/usr/bin/etcd" CONSUL_BIN="/usr/bin/consul" ./test
